"""add_buong_giuong

Revision ID: 216a4f71471b
Revises: bdbc5ead486e
Create Date: 2026-06-25 16:51:59.127582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '216a4f71471b'
down_revision: Union[str, None] = 'bdbc5ead486e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benh_an', sa.Column('ma_buong', sa.String(length=10), nullable=True))
    op.add_column('benh_an', sa.Column('ma_giuong', sa.String(length=10), nullable=True))
    op.create_foreign_key(None, 'benh_an', 'buong', ['ma_buong'], ['ma_buong'])
    op.create_foreign_key(None, 'benh_an', 'giuong', ['ma_giuong'], ['ma_giuong'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'benh_an', type_='foreignkey')
    op.drop_constraint(None, 'benh_an', type_='foreignkey')
    op.drop_column('benh_an', 'ma_giuong')
    op.drop_column('benh_an', 'ma_buong')
    # ### end Alembic commands ###
