"""add_trang_thai_ngay_kham_to_kham_benh_and_fks

Revision ID: 38161b76d3c7
Revises: 20260610_000008
Create Date: 2026-06-11 19:12:41.391994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38161b76d3c7'
down_revision: Union[str, None] = '20260610_000008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('di_tuyen_sau_dieu_tri', sa.Column('ma_giay_gt', sa.String(length=10), nullable=True))
    op.create_foreign_key(None, 'di_tuyen_sau_dieu_tri', 'giay_gioi_thieu', ['ma_giay_gt'], ['ma_giay_gt'], ondelete='CASCADE')
    op.add_column('don_thuoc', sa.Column('ma_kham_benh', sa.String(length=10), nullable=True))
    op.create_foreign_key(None, 'don_thuoc', 'kham_benh', ['ma_kham_benh'], ['ma_kham_benh'], ondelete='CASCADE')
    op.add_column('kham_benh', sa.Column('trang_thai', sa.String(length=20), nullable=True))
    op.add_column('kham_benh', sa.Column('ngay_kham', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kham_benh', 'ngay_kham')
    op.drop_column('kham_benh', 'trang_thai')
    op.drop_constraint(None, 'don_thuoc', type_='foreignkey')
    op.drop_column('don_thuoc', 'ma_kham_benh')
    op.drop_constraint(None, 'di_tuyen_sau_dieu_tri', type_='foreignkey')
    op.drop_column('di_tuyen_sau_dieu_tri', 'ma_giay_gt')
    # ### end Alembic commands ###
