"""add_ma_lay_mau_to_phieu_kham_suc_khoe

Revision ID: 5a67d8f99a1b
Revises: 20260623_000002
Create Date: 2026-06-23 19:13:07.639327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a67d8f99a1b'
down_revision: Union[str, None] = '20260623_000002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nguoi_dung_ten_dang_nhap', table_name='nguoi_dung')
    op.drop_constraint('uq_nguoi_dung_ten_dang_nhap', 'nguoi_dung', type_='unique')
    op.add_column('phieu_kham_suc_khoe', sa.Column('ma_lay_mau', sa.String(length=4), nullable=True))
    op.create_unique_constraint(None, 'phieu_kham_suc_khoe', ['ma_lay_mau'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'phieu_kham_suc_khoe', type_='unique')
    op.drop_column('phieu_kham_suc_khoe', 'ma_lay_mau')
    op.create_unique_constraint('uq_nguoi_dung_ten_dang_nhap', 'nguoi_dung', ['ten_dang_nhap'])
    op.create_index('ix_nguoi_dung_ten_dang_nhap', 'nguoi_dung', ['ten_dang_nhap'], unique=False)
    # ### end Alembic commands ###
