"""add_trang_thai_ma_kham_benh_to_benh_an_and_bnrv

Revision ID: 902139dfac45
Revises: ec2a2d579aba
Create Date: 2026-06-25 09:04:12.181893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '902139dfac45'
down_revision: Union[str, None] = 'ec2a2d579aba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benh_an', sa.Column('ma_kham_benh', sa.String(length=10), nullable=True))
    op.add_column('benh_an', sa.Column('trang_thai', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'benh_an', 'kham_benh', ['ma_kham_benh'], ['ma_kham_benh'], ondelete='CASCADE')
    op.add_column('benh_nhan_ra_vao', sa.Column('ma_kham_benh', sa.String(length=10), nullable=True))
    op.create_foreign_key(None, 'benh_nhan_ra_vao', 'kham_benh', ['ma_kham_benh'], ['ma_kham_benh'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'benh_nhan_ra_vao', type_='foreignkey')
    op.drop_column('benh_nhan_ra_vao', 'ma_kham_benh')
    op.drop_constraint(None, 'benh_an', type_='foreignkey')
    op.drop_column('benh_an', 'trang_thai')
    op.drop_column('benh_an', 'ma_kham_benh')
    # ### end Alembic commands ###
