"""add_ngay_nhap_vien_to_benh_an

Revision ID: bdbc5ead486e
Revises: 902139dfac45
Create Date: 2026-06-25 15:32:43.963617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdbc5ead486e'
down_revision: Union[str, None] = '902139dfac45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('benh_an', sa.Column('ngay_nhap_vien', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('benh_an', 'ngay_nhap_vien')
    # ### end Alembic commands ###
