"""add_ma_kham_benh_to_giay_gioi_thieu

Revision ID: ec2a2d579aba
Revises: e9d1b2c3a4f5
Create Date: 2026-06-24 09:00:02.301490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec2a2d579aba'
down_revision: Union[str, None] = 'e9d1b2c3a4f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giay_gioi_thieu', sa.Column('ma_kham_benh', sa.String(length=10), nullable=True))
    op.create_foreign_key(None, 'giay_gioi_thieu', 'kham_benh', ['ma_kham_benh'], ['ma_kham_benh'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'giay_gioi_thieu', type_='foreignkey')
    op.drop_column('giay_gioi_thieu', 'ma_kham_benh')
    # ### end Alembic commands ###
