"""add_ma_nguoi_dung_to_phieu_cham_soc

Revision ID: f352dc123a83
Revises: 216a4f71471b
Create Date: 2026-06-29 09:21:26.690804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f352dc123a83'
down_revision: Union[str, None] = '216a4f71471b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phieu_cham_soc', sa.Column('ma_nguoi_dung', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phieu_cham_soc', 'ma_nguoi_dung')
    # ### end Alembic commands ###
